/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingPlanRouteImport } from './routes/training-plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as ActivityActivityIdRouteImport } from './routes/activity.$activityId'

const TrainingPlanRoute = TrainingPlanRouteImport.update({
  id: '/training-plan',
  path: '/training-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ActivityActivityIdRoute = ActivityActivityIdRouteImport.update({
  id: '/activity/$activityId',
  path: '/activity/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/training-plan': typeof TrainingPlanRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/training-plan': typeof TrainingPlanRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/training-plan': typeof TrainingPlanRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/training-plan'
    | '/activity/$activityId'
    | '/settings/connections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/training-plan'
    | '/activity/$activityId'
    | '/settings/connections'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/training-plan'
    | '/activity/$activityId'
    | '/settings/connections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TrainingPlanRoute: typeof TrainingPlanRoute
  ActivityActivityIdRoute: typeof ActivityActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-plan': {
      id: '/training-plan'
      path: '/training-plan'
      fullPath: '/training-plan'
      preLoaderRoute: typeof TrainingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/activity/$activityId': {
      id: '/activity/$activityId'
      path: '/activity/$activityId'
      fullPath: '/activity/$activityId'
      preLoaderRoute: typeof ActivityActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsConnectionsRoute: SettingsConnectionsRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TrainingPlanRoute: TrainingPlanRoute,
  ActivityActivityIdRoute: ActivityActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
